//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class All
    {
        public int id { get; set; }
        public int idRole { get; set; }
        public string FIO { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Number { get; set; }
        public string Passport { get; set; }
        public System.DateTime DateBorn { get; set; }
        public string LastEnetr { get; set; }
        public string TypeEnter { get; set; }
        public string Gender { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
